# This is a basic workflow to help you get started with Actions

on: [push, pull_request]
name: Test
jobs:
  exakat:
    name: Exakat Scan II
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Exakat
      uses: docker://exakat/exakat-ga
